create table if not exists public.voyayaha_places (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  city text,
  region text,
  country text,
  latitude double precision not null,
  longitude double precision not null,
  category text,
  description text,
  best_for text,
  image_url text,
  source_url text,
  source text default 'Voyayaha',
  verified boolean not null default false,
  published boolean not null default false,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists voyayaha_places_published_idx
  on public.voyayaha_places (published, verified);

create index if not exists voyayaha_places_city_idx
  on public.voyayaha_places (lower(city));

-- RLS keeps the table closed to anonymous browser access.
-- The Render backend uses the service-role key, which bypasses RLS.
alter table public.voyayaha_places enable row level security;

-- Optional: automatically update updated_at when a row changes.
create or replace function public.set_voyayaha_places_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists voyayaha_places_updated_at on public.voyayaha_places;
create trigger voyayaha_places_updated_at
before update on public.voyayaha_places
for each row execute function public.set_voyayaha_places_updated_at();
